### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by vr6syncro** [t1m0thyj/VoiceCreateBot#1]
hello, i get a error maybe u could help.

```
Traceback (most recent call last):
  File "voicecreate.py", line 18, in <module>
    DISCORD_TOKEN = os.environ['xyz']
NameError: name 'xyz' is not defined
```

**Comment by t1m0thyj** [comment]
The syntax `os.environ['xyz']` is looking for the value of an environment variable named XYZ. The error happens if you don't have that environment variable defined.

In Linux, you can define an environment variable in a Bash terminal like this: `export XYZ='some_token'`
